---
title: "Bias examples"
output: html_document
date: "2024-10-04"
---

```{r}
data_folder <- here::here("Data", "National_Data")
code_folder <- here::here("Code", "Analysis")
figure_folder <- here::here("Figures")
source(here::here(code_folder, "helper_functions.R"))

library(ggplot2)
library(patchwork)
hosps <- readRDS(file.path(data_folder, "HHS_real_time.RData"))
hosp_dates <- as.Date(names(hosps))
hfrs_nhcs <- readRDS(here::here(data_folder, "HFRs_NHCS_rescaled.RData"))
hfr_dates <- as.Date(names(hfrs_nhcs))
```


############ Figure 1 ############

Example A: Changing HFR

```{r}
# Deaths come from noiseless model with real hosps, different HFRs, and reasonable delay distribution
# Compare real change to version with smaller change in magnitude during that window. Shifting to emphasize the bias is due to the change in HFRs, not merely their magnitude.
d <- 75
delay_distr_med <- make_delay_distr(Mean=20, Sd=round(20*.9), d)
n_pts <- 200
n_ests <- n_pts - d

t0 <- as.Date("2022-02-01")
hosp_start_idx <- which(hosp_dates==t0)

chging_hfrs <- hfrs_nhcs[hfr_dates %in% as.Date((t0-d):(t0-d+n_pts-1))]
# Shrink the change in magnitude
flatter_hfrs <- (chging_hfrs-min(chging_hfrs))*0.25+median(chging_hfrs)*.85


calc_nish_hfrs <- function(hosps, hfrs, delay_distr) {
  est_hfrs_flat <- sapply(1:n_ests, function(t_idx) {
    trailing_hosps <- hosps[(t_idx):(d+t_idx)]
    trailing_hfrs <- hfrs[(t_idx):(d+t_idx)]
    exp_deaths <- sum(rev(delay_distr)*trailing_hosps*trailing_hfrs)
    denom <- sum(rev(delay_distr)*trailing_hosps)
    exp_deaths/denom
  })
  return(est_hfrs_flat)
}
est_idx <- (d+1):n_pts

hosps_window <- hosps[(hosp_start_idx-d):(hosp_start_idx+n_ests-1)]
est_flat <- calc_nish_hfrs(hosps_window, flatter_hfrs, delay_distr_med)
est_chging <- calc_nish_hfrs(hosps_window, chging_hfrs, delay_distr_med)
sources <- c("True", "Estimated"); types <- c("Original", "Flatter")
df <- data.frame(t=t0+rep(1:n_ests, 4)-1,
                 HFRs=c(chging_hfrs[est_idx], flatter_hfrs[est_idx], est_chging, est_flat),
                 HFR=factor(rep(sources, each=n_ests*2), levels=sources),
                 Variation=factor(rep(rep(types, each=n_ests), 2), levels=types))
Plot <- ggplot(df, aes(x=t, y=HFRs, color=Variation, linetype=HFR)) +
  geom_line() + ggtitle("Effect of changing severity rate") + 
  xlab("") + theme_bw() + #Date
  guides(linetype = guide_legend(order = 1), color = guide_legend(order = 2)) +
  theme(legend.position = "bottom",
        plot.title=element_text(size=23),
        legend.text = element_text(size=19),
        legend.title=element_text(size=19),
        axis.title.y=element_text(size=19),
        legend.spacing.y = unit(0.5, "cm"),
        legend.margin = margin(t = -10),
        legend.box = "vertical") + 
  scale_color_manual(values = c("Original" = "black", "Flatter" = "blue"))

ggsave(file.path(figure_folder, "Simulated", "toy_chging_hfr.pdf"), 
       plot = Plot, device = "pdf", width = 7, height = 7)

Plot
```


Example B: Short and long delay distribution

```{r}
short_mean <- 12
long_mean <- 28
delay_distr_short <- make_delay_distr(Mean=short_mean, Sd=round(short_mean*.9), d)
delay_distr_long <- make_delay_distr(Mean=long_mean, Sd=round(long_mean*.9), d)

est_short <- calc_nish_hfrs(hosps_window, chging_hfrs, delay_distr_short)
est_med <- calc_nish_hfrs(hosps_window, chging_hfrs, delay_distr_med)
est_long <- calc_nish_hfrs(hosps_window, chging_hfrs, delay_distr_long)

sources <- c("True", "Estimated")
types <- c("12", "20", "28")

# Keep True in Type for plotting but handle later
df <- data.frame(
  t = t0+rep(1:n_ests, 4)-1,
  HFRs = c(chging_hfrs[est_idx], est_short, est_med, est_long),
  HFR = factor(c(rep("True", n_ests), rep("Estimated", n_ests*3)), levels = sources),
  Type = factor(c(rep("True", n_ests), rep(types, each=n_ests)), levels = c("True", types))  
)

delayPlot <- ggplot(df, aes(x = t, y = HFRs, linetype = HFR, color = Type)) +
  geom_line(aes(group = interaction(HFR, Type))) +  # Group by HFR and Type
  # Manually set color, exclude True from legend
  scale_color_manual(breaks = types,
    values = c("True" = "black", "12" = "green3", "20" = "red2", "28" = "blue")) +
  ggtitle("Effect of true delay distrbution") +
  labs(color="Delay mean") + xlab("") +#Date
  theme_bw() +
  guides(linetype = guide_legend(order = 1), color = guide_legend(order = 2)) +
  theme(legend.position = "bottom",
        plot.title=element_text(size=23),
        legend.text = element_text(size=19),
        legend.title=element_text(size=19),
        axis.title.y=element_text(size=19),
        legend.spacing.y = unit(0.5, "cm"),
        legend.margin = margin(t = -10),
        legend.box = "vertical")

dfDistr <- data.frame(t=rep(0:d, 3),
                      Delay=c(delay_distr_short, delay_distr_med, delay_distr_long),
                      Type=rep(types, each=d+1))
delay_inset <- ggplot(dfDistr, aes(x=t, y=Delay, color=Type)) + geom_line() + theme_bw() + 
  scale_color_manual(breaks = types,
    values = c("True" = "black", "12" = "green3", "20" = "red2", "28" = "blue")) +
  theme(legend.position="none", plot.background = element_blank(),
        plot.title = element_text(size = 14),
        axis.title = element_text(size = 14)) + 
  xlab("Days after primary event") + ylab("") + ggtitle("Delay distribution")

delayPlotFinal <- delayPlot + annotation_custom(ggplotGrob(delay_inset), xmin=t0, xmax=t0+60, ymax=.14)

ggsave(file.path(figure_folder, "Simulated", "toy_delay_distr.pdf"),
       plot = delayPlotFinal, device = "pdf", width = 7, height = 7)

delayPlotFinal
```

Example C: Primary incidence

```{r}
max_obs <- max(hosps_window[est_idx]); min_obs <- min(hosps_window[est_idx])
sigmoid <- function(x) {1/(1+exp(-x))}

alt_hosps1 <- sigmoid(seq(-10, 5, length.out=n_pts))*(max_obs-min_obs) + min_obs
alt_hosps2 <- (1-sigmoid(seq(-10, 5, length.out=n_pts)))*(max_obs-min_obs) + min_obs
names(alt_hosps1) <- names(hosps_window)
names(alt_hosps2) <- names(hosps_window)

hfrs_Original_hosps <- calc_nish_hfrs(hosps_window, chging_hfrs, delay_distr_med)
hfrs_alt_hosps1 <- calc_nish_hfrs(alt_hosps1, chging_hfrs, delay_distr_med)
hfrs_alt_hosps2 <- calc_nish_hfrs(alt_hosps2, chging_hfrs, delay_distr_med)

sources <- c("True", "Estimated")
types <- c("Original", "Rising", "Falling")
df <- data.frame(
  t = t0+rep(1:n_ests, 4)-1,
  HFRs = c(chging_hfrs[est_idx], hfrs_Original_hosps, hfrs_alt_hosps1, hfrs_alt_hosps2),
  HFR = factor(c(rep("True", n_ests), rep("Estimated", n_ests*3)), levels = sources),
  Type = factor(c(rep("True", n_ests), rep(types, each=n_ests)), levels = c("True", types))  
)

hospPlot <- ggplot(df, aes(x = t, y = HFRs, linetype = HFR, color = Type)) +
  geom_line(aes(group = interaction(HFR, Type))) +  # Group by HFR and Type
  scale_color_manual(breaks = types,
    values = c("True" = "black", "Rising" = "green3", "Original" = "red2", "Falling" = "blue")) +  
  ggtitle("Effect of primary incidence") +
  labs(color="Primary curve") + xlab("") +# xlab("Date") +
  theme_bw() + 
  guides(linetype = guide_legend(order = 1), color = guide_legend(order = 2)) +
  theme(legend.position = "bottom",
        plot.title=element_text(size=23),
        legend.text = element_text(size=19),
        legend.title=element_text(size=19),
        axis.title.y=element_text(size=19),
        legend.spacing.y = unit(0.5, "cm"),
        legend.margin = margin(t = -10),
        legend.box = "vertical") 

dfHosp <- data.frame(t=rep(as.Date(names(hosps_window)[est_idx]), 3),
                      Hosp=c(hosps_window[est_idx], alt_hosps1[est_idx], alt_hosps2[est_idx]),
                      Type=factor(rep(types, each=length(est_idx)), levels=types))
hosp_inset <- ggplot(dfHosp, aes(x=t, y=Hosp, color=Type, group=Type)) + geom_line() + theme_bw() + 
  scale_color_manual(breaks = types,
    values = c("Rising" = "green3", "Original" = "red2", "Falling" = "blue")) +  
  theme(legend.position="none", plot.background = element_blank(),
        plot.title = element_text(size = 14)
        ) + 
  xlab("") + ylab("") + ggtitle("Hospitalizations")
hosp_inset


hospPlotFinal <- hospPlot + annotation_custom(ggplotGrob(hosp_inset), xmin=t0, xmax=t0+60, ymax=.14)
hospPlotFinal

ggsave(file.path(figure_folder, "Simulated", "toy_chging_primary.pdf"),
       plot = hospPlotFinal, device = "pdf", width = 7, height = 7)
```





############ Figure 2 ############

```{r}
shorter_mean <- 16
longer_mean <- 24
delay_distr_shorter <- make_delay_distr(Mean=shorter_mean, Sd=round(shorter_mean*.9), d)
delay_distr_Original <- make_delay_distr(Mean=20, Sd=round(shorter_mean*.9), d)
delay_distr_longer <- make_delay_distr(Mean=longer_mean, Sd=round(longer_mean*.9), d)

```

```{r}
first_death_date <- max(hfr_dates[1], hosp_dates[1])+d
last_death_date <- min(hfr_dates[length(hfr_dates)], hosp_dates[length(hosps)])

death_dates <- seq(first_death_date, last_death_date, by="day")
est_dates <- seq(as.Date("2021-11-01"), as.Date("2022-07-01"), by="day")
noiseless_deaths <- compute_noiseless_deaths(hosps, hfrs_nhcs, delay_distr_Original, est_dates)

n_ests <- length(est_dates)

# 16. Could also use mean of delay distribution, 20
gt_hfrs <- hfrs_nhcs[hfr_dates %in% est_dates]
optimal_lag <- compute_optimal_lag(hosps, noiseless_deaths)
lagged_hfrs <- compute_lagged_hfrs(hosps, noiseless_deaths, l=optimal_lag, dates=est_dates) 
conv_hfrs_oracle <- compute_conv_hfrs(hosps, noiseless_deaths, est_dates, delay_distr_Original)
conv_hfrs_shorter <- compute_conv_hfrs(hosps, noiseless_deaths, est_dates, delay_distr_shorter)
conv_hfrs_longer <- compute_conv_hfrs(hosps, noiseless_deaths, est_dates, delay_distr_longer)
```

```{r}

R_gamma_shorter <- compute_R_gammas(hosps, delay_distr_Original, delay_distr_shorter, est_dates)
R_gamma_Original <- compute_R_gammas(hosps, delay_distr_Original, delay_distr_Original, est_dates)
R_gamma_longer <- compute_R_gammas(hosps, delay_distr_Original, delay_distr_longer, est_dates)
lagged_distr <- rep(0, d+1); lagged_distr[optimal_lag+1] <- 1
R_gamma_lagged <- compute_R_gammas(hosps, delay_distr_Original, lagged_distr, est_dates)

```

```{r}
sources <- c("True", "Estimated")
types <- c("Original", "Light-tailed", "Heavy-tailed", "Lagged")
# Keep True in Type for plotting but handle later
df <- data.frame(
  t = rep(est_dates, 5),
  HFRs = c(gt_hfrs, conv_hfrs_oracle, conv_hfrs_shorter, conv_hfrs_longer, lagged_hfrs),
  HFR = factor(c(rep("True", n_ests), rep("Estimated", n_ests*4)), levels = sources),
  Type = factor(c(rep("True", n_ests), rep(types, each=n_ests)), 
                levels = c("True", types))  
)

mispPlot <- ggplot(df, aes(x = t, y = HFRs, linetype = HFR, color = Type)) +
  geom_line(aes(group = interaction(HFR, Type))) +  # Group by HFR and Type
  scale_color_manual(breaks = types,
    values = c("True" = "black", "Light-tailed" = "green3", "Original" = "red2", 
               "Heavy-tailed" = "blue", "Lagged" = "magenta")) +  
  ggtitle("HFR estimates, misspecified delay distribution") +
  labs(color="Delay distribution") + xlab("Date") +
  theme_bw() + xlab("") +
  guides(linetype = guide_legend(order = 1), color = guide_legend(order = 2)) +
  scale_x_date(date_breaks = "1 month", labels = NULL) +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 13),
        plot.title = element_text(size = 17),
        axis.text.x = element_blank(),
        legend.spacing.y = unit(0.5, "cm"),
        legend.margin = margin(t = -10))
mispPlot

delayTypes <- c("Light-tailed", "Original", "Heavy-tailed")
dfDistr <- data.frame(t=rep(0:d, 3),
                      Delay=c(delay_distr_shorter, delay_distr_Original, delay_distr_longer),
                      Type=rep(delayTypes, each=d+1))
delay_inset <- ggplot(dfDistr, aes(x=t, y=Delay, color=Type)) + 
  geom_line() + theme_bw() + 
  scale_color_manual(breaks = delayTypes, 
                     values = c("Light-tailed" = "green3", "Original" = "red2", "Heavy-tailed" = "blue")) +  
  theme(legend.position="none",
        plot.title = element_text(size = 12),
        axis.title = element_text(size = 10),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) + 
  xlab("") +
  # xlab("Days after primary event") + 
  ylab("") + ggtitle("Delay distribution")

mispPlotInlaid <- mispPlot + 
  annotation_custom(ggplotGrob(delay_inset), xmin=est_dates[1]-15, xmax=est_dates[1]+67, 
                    ymin=.08, ymax=.148)
mispPlotInlaid
```

```{r}
df2 <- data.frame(
  t = rep(est_dates, 4),
  Ratios = c(R_gamma_Original, R_gamma_shorter, R_gamma_longer, R_gamma_lagged),
  Type = factor(rep(types, each=n_ests), levels = types)  
)

ratioPlot <- ggplot(df2, aes(x = t, y = Ratios, color = Type)) +
  geom_line() +  # Group by HFR and Type
  scale_color_manual(breaks = types,
    values = c("Light-tailed" = "green3", "Original" = "red2", 
               "Heavy-tailed" = "blue", "Lagged" = "magenta")) +  
  ggtitle(expression("Ratios A"^gamma)) +
  theme_bw() + xlab("") +
  scale_x_date(date_breaks = "1 month", labels = NULL) +
  theme(legend.position = "none",
        #plot.title = element_text(size = 14),
        axis.text.x = element_blank())
ratioPlot

df3 <- data.frame(t = est_dates, Hosps=hosps[hosp_dates %in% est_dates])

hospPlot <- ggplot(df3, aes(x = t, y = Hosps)) +
  geom_line() +  ggtitle("Hospitalizations") +
  scale_x_date(date_breaks = "1 month",date_labels = "%b %Y") + 
  theme_bw() +
  xlab("") +
  theme(legend.position = "none",
        )
hospPlot

```

```{r, fig.width=7, fig.height=7}
full_misp_plot <- mispPlotInlaid / ratioPlot / hospPlot + plot_layout(heights = c(3, 1, 1))
full_misp_plot
ggsave(file.path(figure_folder, "Simulated", "toy_misp.pdf"), 
       plot = full_misp_plot, device = "pdf", width = 8, height = 7) 

```


