```{r}
git_directory <- system("git rev-parse --show-toplevel", intern = TRUE)
data_folder <- file.path(git_directory, "Data", "National_Data")
code_folder <- file.path(git_directory, "Code", "Analysis")
figure_folder <- file.path(git_directory, "Figs")
source(file.path(code_folder, "helper_functions.R"))
library(tidyverse)
library(epidatr)
library(extraDistr)
library(patchwork)


```



### Load NHCS HFRs
```{r}
# nhcs_hfrs_all <- readRDS(file.path(data_folder, "smoothed_hfrs.RData"))
# nhcs_hfr_dates <- as.Date(names(nhcs_hfrs_all))
nhcs_hfrs_all <- readRDS(file.path(data_folder, "hfrs_rescaled_v2.RData"))
nhcs_hfr_dates <- as.Date(names(nhcs_hfrs_all))
```



## Hospitalizations


```{r}
hhs_df <- data.frame(pub_covidcast(source="hhs",signals= "confirmed_admissions_covid_1d_7dav", 
                                   geo_type = "nation", geo_values="*", 
                                   time_type="day"))
hosp_dates_all <- as.Date(hhs_df$time_value)
hhs_hosps_all <- hhs_df$value

first_hosp_date <- as.Date("2020-07-28") # Basically all 0 before this
first_ok_date <- max(first_hosp_date, min(nhcs_hfr_dates))
valid_idx <- hosp_dates_all>=first_ok_date & hosp_dates_all<=max(nhcs_hfr_dates)
hosp_dates <- hosp_dates_all[valid_idx]
hhs_hosps <- hhs_hosps_all[valid_idx]; names(hhs_hosps) <- as.Date(hosp_dates)

nhcs_hfrs <- nhcs_hfrs_all[nhcs_hfr_dates %in% hosp_dates]

plot(hosp_dates, hhs_hosps, type="l", xlab="Date", xaxt="n", ylab="Total Weekly Hosps", main="Weekly Hospitalizations")
date_ticks <- seq(from = min(hosp_dates), to = max(hosp_dates), by = "3 months")
axis(1, at = date_ticks, labels = format(date_ticks, "%Y-%m"))

```


## Get delay distribution

Get delay distributions for Nishiura method

```{r}
d <- 75
short_mean <- 12
long_mean <- 24
delay_distr_short <- make_delay_distr(Mean=short_mean, Sd=round(short_mean*.9), d)
delay_distr_long <- make_delay_distr(Mean=long_mean, Sd=round(long_mean*.9), d)
```

```{r}
# Ns <- c(28611, 1700, 16641, 16903)
# means <- c(10.20, 14.06, 14.84, 9.24)
# sds <- c(9.51, 14.31, 12.35, 7.64)
# gamma_mean <- sum(means*Ns/sum(Ns)) # Weighted average hosp-to-death time
# gamma_sd <- sum(sds*Ns/sum(Ns)) # Weighted average of SDs
# 
# # delay_distr_short <- readRDS(file.path(data_folder, "delay_distr_short.RData"))
# d <- 75
# params <- get_gamma_params(Mean=gamma_mean, Sd=gamma_sd)
# shape <- params[1]; rate <- params[2]
# 
# delay_distr_short <- ddgamma(0:d, shape, rate)
# delay_mean <- sum(0:d*delay_distr_short)
# print(c(gamma_mean, delay_mean))
# print(c(gamma_sd, sqrt(sum(delay_distr_short*(0:d-delay_mean)**2))))
# plot(0:d, delay_distr_short)
# 
# # Delay distribution for report date
# # gamma_mean_report <- round(gamma_mean) + 9
# # gamma_sd_report <- round(gamma_sd) + 6
# gamma_mean_report <- 28
# gamma_sd_report <- 21
# params <- get_gamma_params(Mean=gamma_mean_report, Sd=gamma_sd_report) 
# shape <- params[1]; rate <- params[2]
# delay_distr_long <- ddgamma(0:d, shape, rate)
# plot(0:d, delay_distr_long)
# 
death_dates <- hosp_dates[(d+1):length(hosp_dates)]

```
## Convolve to simulate deaths

```{r}
sim_deaths_short <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- nhcs_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_short))
}); names(sim_deaths_short) <- death_dates

sim_deaths_long <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- nhcs_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_long))
}); names(sim_deaths_long) <- death_dates

plot(sim_deaths_short, type="l");lines(sim_deaths_long, type="l", col="red")
```
## Compute HFRs


```{r}
lag_short <- round(sum(0:d*delay_distr_short))
# Estimate HFRs weekly, & offset to account for potential smoothing 
est_dates <- death_dates[seq(1+7*6, length(death_dates), by=7)]
hfrs_lagged_short <- compute_lagged_hfrs(hhs_hosps, sim_deaths_short, lag_short, w=1, dates=est_dates)
hfrs_conv_short <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_short, est_dates, delay_distr_short, w=1)

gt_hfrs <- nhcs_hfrs[hosp_dates %in% est_dates]
HFRtypes <- c("Ground Truth", "Convolutional Ratio", "Lagged Ratio")
dfHFRshort <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs, hfrs_conv_short, hfrs_lagged_short), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRshort, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (NHCS)",
          subtitle="Short Delay Distribution") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())


```
Repeat on long window
```{r}
lag_long <- round(sum(0:d*delay_distr_long))
# # Using correlation-maximizing lag doesn't improve; actually hurts a bit
# cc <- ccf(hhs_hosps[(d+1):length(hhs_hosps)], sim_deaths_long, lag.max=30, plot=FALSE)
# max_correlation_lag <- which.max(abs(cc$acf))
# lag_long <- abs(cc$lag[max_correlation_lag])

# Estimate HFRs weekly, & offset to account for potential smoothing 
est_dates <- death_dates[seq(1+7*6, length(death_dates), by=7)]
hfrs_lagged_long <- compute_lagged_hfrs(hhs_hosps, sim_deaths_long, lag_long, w=1, dates=est_dates)
hfrs_conv_long <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_long, est_dates, delay_distr_long, w=1)

gt_hfrs <- nhcs_hfrs[hosp_dates %in% est_dates]
dfHFRlong <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs, hfrs_conv_long, hfrs_lagged_long), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRlong, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (NHCS)",
          subtitle="Long Delay Distribution") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())
```


```{r}
# Multiply by 7: 21 days (19 on its own here)
cc <- ccf(gt_hfrs, hfrs_conv_long, lag.max=30, plot=TRUE)
max_correlation_lag <- which.max(abs(cc$acf))
lag_at_max_cor <- cc$lag[max_correlation_lag]
print(paste("The lag that maximizes the correlation is:", abs(lag_at_max_cor*7), " days"))
```

# Flat HFR

```{r}
flat_hfrs <- rep(0.1, length(nhcs_hfrs)); names(flat_hfrs) <- hosp_dates
sim_deaths_short_flat <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- flat_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_short))
}); names(sim_deaths_short_flat) <- death_dates

hfrs_lagged_short_flat <- compute_lagged_hfrs(hhs_hosps, sim_deaths_short_flat, lag_short, w=1, dates=est_dates)
hfrs_conv_short_flat <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_short_flat, est_dates, delay_distr_short, w=1)
gt_hfrs_flat <- flat_hfrs[hosp_dates %in% est_dates]
dfHFRflat <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_flat, hfrs_conv_short_flat, hfrs_lagged_short_flat), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRflat, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (Flat)") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())

```

```{r}
flat_hfrs <- rep(0.1, length(nhcs_hfrs)); names(flat_hfrs) <- hosp_dates
sim_deaths_long_flat <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- flat_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_long))
}); names(sim_deaths_long_flat) <- death_dates

hfrs_lagged_long_flat <- compute_lagged_hfrs(hhs_hosps, sim_deaths_long_flat, lag_long, w=1, dates=est_dates)
hfrs_conv_long_flat <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_long_flat, est_dates, delay_distr_long, w=1)
gt_hfrs_flat <- flat_hfrs[hosp_dates %in% est_dates]
dfHFRflat <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_flat, hfrs_conv_long_flat, hfrs_lagged_long_flat), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRflat, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (Flat)") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())

```


# Inverted HFR


```{r}
inv_hfrs <- (1/nhcs_hfrs)*min(nhcs_hfrs)*max(nhcs_hfrs)
sim_deaths_short_inv <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- inv_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_short))
}); names(sim_deaths_short_inv) <- death_dates

hfrs_lagged_short_inv <- compute_lagged_hfrs(hhs_hosps, sim_deaths_short_inv, lag_short, w=1, dates=est_dates)
hfrs_conv_short_inv <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_short_inv, est_dates, delay_distr_short, w=1)
gt_hfrs_inv <- inv_hfrs[hosp_dates %in% est_dates]
dfHFRshort_inv <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_inv, hfrs_conv_short_inv, hfrs_lagged_short_inv), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRshort_inv, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (Inverted)",
          subtitle="Short Delay Distribution") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())

```

Repeat with longer delay

```{r}
inv_hfrs <- (1/nhcs_hfrs)*min(nhcs_hfrs)*max(nhcs_hfrs)
sim_deaths_long_inv <- sapply(death_dates, function(t) {
  trailing_dates <- seq(t-d, t, by="day")
  trailing_hfrs <- inv_hfrs[hosp_dates %in% trailing_dates]
  hosps_in_trailing_window <- hhs_hosps[hosp_dates %in% trailing_dates]
  exp_deaths <- sum(hosps_in_trailing_window * trailing_hfrs * rev(delay_distr_long))
}); names(sim_deaths_long_inv) <- death_dates

hfrs_lagged_long_inv <- compute_lagged_hfrs(hhs_hosps, sim_deaths_long_inv, lag_long, w=1, dates=est_dates)
hfrs_conv_long_inv <- compute_ahfrs_dynamic(hhs_hosps, sim_deaths_long_inv, est_dates, delay_distr_long, w=1)
gt_hfrs_inv <- inv_hfrs[hosp_dates %in% est_dates]
dfHFRlong_inv <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_inv, hfrs_conv_long_inv, hfrs_lagged_long_inv), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
ggplot(data=dfHFRlong_inv, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Simulation: Estimated vs True HFRs (Inverted)",
          subtitle="Short Delay Distribution") +
  scale_x_date(breaks = seq(as.Date("2020-10-01"), max(est_dates), by = "3 months"), date_labels = "%b %Y") +
  xlab("") +
  theme(legend.position="bottom",
        legend.title=element_blank())
```

# Offset analysis

```{r}
# Multiply by 7: 21 days
cc <- ccf(gt_hfrs_inv, hfrs_conv_long_inv, lag.max=10, plot=TRUE)
max_correlation_lag <- which.max(abs(cc$acf))
lag_at_max_cor <- cc$lag[max_correlation_lag]
print(paste("The lag that maximizes the correlation is:", abs(lag_at_max_cor*7), " days"))
```

```{r}
calc_offset <- function(true_hfrs, est_hfrs, max_lag=10, weekly=TRUE) {
  cc <- ccf(true_hfrs, est_hfrs, lag.max=max_lag, plot=FALSE)
  max_correlation_lag <- which.max(abs(cc$acf))
  lag_at_max_cor <- cc$lag[max_correlation_lag]
  lag_at_max_cor <- abs(ifelse(weekly, lag_at_max_cor*7, lag_at_max_cor))
  return(lag_at_max_cor)
}
paste0("Offset, True HFRs with short delay: ", calc_offset(gt_hfrs_inv, hfrs_conv_short))
paste0("Offset, True HFRs with long delay: ", calc_offset(gt_hfrs_inv, hfrs_conv_long))
paste0("Offset, Inverted HFRs with short delay: ", calc_offset(gt_hfrs_inv, hfrs_conv_short_inv))
paste0("Offset, Inverted HFRs with long delay: ", calc_offset(gt_hfrs_inv, hfrs_conv_long_inv))


```




```{r}
cc <- ccf(hhs_hosps[(d+1):length(hhs_hosps)], sim_deaths_long_inv, lag.max=50, plot=TRUE)
max_correlation_lag <- which.max(abs(cc$acf))
lag_at_max_cor <- cc$lag[max_correlation_lag]
print(paste("The lag that maximizes the correlation is:", lag_at_max_cor))
```

```{r, fig.width=9, fig.height=7}

# titlesize <- 12
p1 <- ggplot(data=dfHFRshort, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("NHCS HFRs",
          subtitle="Short Delay Distribution") +
  xlab("") + theme_bw()
p2 <- ggplot(data=dfHFRlong, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("",subtitle="Long Delay Distribution") +
  xlab("") + theme_bw()
p3 <- ggplot(data=dfHFRshort_inv, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Inverted NHCS HFRs") +
  xlab("") + theme_bw()
p4 <- ggplot(data=dfHFRlong_inv, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("") +#, subtitle="Long Delay Distribution"
  xlab("") + theme_bw() 

dfHFRflat <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_flat, hfrs_conv_short_flat, hfrs_lagged_short_flat), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
p5 <- ggplot(data=dfHFRflat, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("Stationary HFR") +
  xlab("") + theme_bw()

dfHFRflat2 <- data.frame(Date=rep(est_dates, length(HFRtypes)),
                 HFR=c(gt_hfrs_flat, hfrs_conv_long_flat, hfrs_lagged_long_flat), 
                 Method=factor(rep(HFRtypes, each=length(est_dates)), levels=HFRtypes))
p6 <- ggplot(data=dfHFRflat2, aes(x = Date, y = HFR, color = Method, linetype=Method)) + 
  geom_line() + labs(color = "HFR", linetype = "HFR") + 
  ggtitle("") +
  xlab("") + theme_bw()

Plot <- ((p1|p2) + plot_layout(tag_level = 'new')) / 
  ((p3|p4) + plot_layout(tag_level = 'new')) / 
  ((p5|p6) + plot_layout(tag_level = 'new')) +
  plot_annotation(title = 'HFRs, Simulated Deaths', tag_levels = c('A', '1')) +
  plot_layout(guides="collect") & 
  theme(legend.position = "bottom",
        legend.title = element_blank())
Plot

ggsave(file.path(figure_folder, "Simulated", "simulated_results.pdf"), plot = Plot, device = "pdf", width = 9, height = 7)
```

