
```{r}
data_folder <- here::here("Data", "National_Data")
code_folder <- here::here("Code", "Analysis")
figure_folder <- here::here("Figures")
source(here::here(code_folder, "helper_functions.R"))

library(epidatr)
library(patchwork)
library(ggplot2)

```

##### Repeat on different states


```{r}
max_jhu_date <- as.Date("2023-03-01")
first_hosp_date <- as.Date("2020-07-28")

jhulist <- list()
nchslist <- list()
hosplist <- list()
BiggestStates <- c("California", "Texas", "Florida", "New York", "Pennsylvania", "Illinois")
BiggestSTs <- c("CA","TX","FL","NY","PA", "IL")
for (i in 1:6) {
  State <- BiggestStates[i]; ST <- BiggestSTs[i]; st <- tolower(ST)
  # Load NCHS deaths (weekly)
  nchs_df <- data.frame(pub_covidcast(source="nchs-mortality",signals= "deaths_covid_incidence_num", 
                                     geo_type = "state", geo_values=st, 
                                     time_type="week"))
  # Convert to daily
  nchs_week_ends <- as.Date(nchs_df$time_value)+6
  nchs_deaths_weekly <- nchs_df$value; names(nchs_deaths_weekly) <- nchs_week_ends
  # Silly, but fixes issue mid-2023 in Illinois
  nchs_deaths_weekly <- nchs_deaths_weekly[nchs_week_ends <= max_jhu_date]
  nchs_week_ends <- nchs_week_ends[nchs_week_ends <= max_jhu_date]
  # nchs_deaths <- rep(nchs_df$value, each=7)/7
  # times <- as.Date(nchs_df$time_value)
  # nchs_dates <- seq(min(times), max(times)+6, by="day")
  # names(nchs_deaths) <- as.Date(nchs_dates)
  # 
  # length(nchs_deaths)
  
  # Load JHU deaths (daily, smoothed)
  jhu_df <- data.frame(pub_covidcast(source="jhu-csse", signals="deaths_incidence_num",#7dav_
                                      geo_type = "state", geo_values=st, 
                                      time_type="day"))
  jhu_dates <- as.Date(jhu_df$time_value)
  jhu_deaths <- jhu_df$value; names(jhu_deaths) <- jhu_dates
  jhu_deaths <- seven_day_smoothing(jhu_deaths, centered = FALSE)
  
  plot(jhu_dates, jhu_deaths, type="l", main=paste("Weekly Deaths,", State), 
       ylab="Deaths", xlab="Dates",ylim=c(0,max(jhu_deaths,nchs_deaths_weekly/7,na.rm=T)))
  lines(nchs_week_ends, nchs_deaths_weekly/7, col="red")
  legend("topright", legend=c("JHU", "NCHS"),
         col=c("black", "red"), lty=1)
  
  # Pull state hospitalizations
  hhs_df <- data.frame(pub_covidcast(source="hhs",signals= "confirmed_admissions_covid_1d", 
                                   geo_type = "state", geo_values=st, 
                                   time_type="day"))
  state_hosps <- hhs_df$value; names(state_hosps) <- hhs_df$time_value
  state_hosps <- state_hosps[names(state_hosps) >= first_hosp_date]
  state_hosps <- seven_day_smoothing(state_hosps, centered = FALSE)
  
  hosplist <- append(hosplist, list(state_hosps))
  jhulist <- append(jhulist, list(jhu_deaths))
  nchslist <- append(nchslist, list(nchs_deaths_weekly))
}



```


```{r}
d <- 75

HFRtypes <- c("Approx. GT", "Convolutional ratio", "Lagged ratio")
dfList <- list()
oracle_lags <- list()
for (i in 1:6) {
  State <- BiggestStates[i]
  jhu_deaths <- jhulist[[i]]
  nchs_deaths <- nchslist[[i]]
  hhs_hosps <- hosplist[[i]]
  
  jhu_dates <- as.Date(names(jhu_deaths))
  nchs_week_ends <- as.Date(names(nchs_deaths))
  hosp_dates <- as.Date(names(hhs_hosps))
  
  # nchs_week_ends <- nchs_dates[seq(7, length(nchs_deaths), by=7)]
  first_est_date <- min(nchs_week_ends[nchs_week_ends > (first_hosp_date + d + 14)])
  est_weeks_state <- seq(first_est_date, min(max(hosp_dates)-4*7, max(nchs_week_ends), as.Date("2022-10-01")), by=7)
  earlier_hosps <- hhs_hosps[names(hhs_hosps) <= as.Date("2022-12-31")]
  
  # Estimate real-time HFRs
  oracle_lag_jhu <- compute_optimal_lag(earlier_hosps, jhu_deaths, verbose=TRUE)
  delay_distr_st <- make_delay_distr(oracle_lag_jhu, round(oracle_lag_jhu*0.9), d)
  
  hfrs_st_lagged <- compute_lagged_hfrs(hhs_hosps, jhu_deaths, l=oracle_lag_jhu, w=7, 
                                        dates=est_weeks_state, real_time=TRUE)
  hfrs_st_conv <- compute_conv_hfrs(hhs_hosps, jhu_deaths, est_weeks_state, delay_distr_st, w=7)

  # Convert NCHS from weekly to daily to compute oracle lag
  nchs_deaths_daily <- rep(nchs_deaths, each=7)/7
  nchs_dates_daily <- seq(min(nchs_week_ends), max(nchs_week_ends)+6, by="day")
  names(nchs_deaths_daily) <- as.Date(nchs_dates_daily)
  oracle_lag_nchs <- compute_optimal_lag(hhs_hosps, nchs_deaths_daily, verbose=TRUE)

  # Convert hospitalizations from daily to weekly 
  # hhs_hosps_weekly <- sapply(est_weeks_state, function(t) {
  #   sum(hhs_hosps[hosp_dates %in% seq(t-6, t, "day")])
  # }); names(hhs_hosps_weekly) <- est_weeks_state
  hfrs_st_retro <- compute_lagged_hfrs(hhs_hosps, nchs_deaths_daily, l=oracle_lag_nchs, w=7,
                                       dates=est_weeks_state, real_time=FALSE, centered=FALSE)
  
  dfHFR <- data.frame(Date=rep(est_weeks_state, length(HFRtypes)),
                   HFR=c(hfrs_st_retro, hfrs_st_conv, hfrs_st_lagged),
                   Method=factor(rep(HFRtypes, each=length(est_weeks_state)), levels=HFRtypes))
  dfList <- append(dfList, list(dfHFR))
  oracle_lags <- append(oracle_lags, list(c(oracle_lag_nchs, oracle_lag_jhu)))
}


```

```{r}
state_data <- list(BiggestStates, dfList, oracle_lags)
saveRDS(state_data, here::here(data_folder, "state_dfs.RData"))
```


```{r}

plotlist <- list()
for (i in 1:6) {
  State <- BiggestStates[i]
  dfHFR <- dfList[[i]]
  lags <- oracle_lags[[i]]
  p <- ggplot(dfHFR, aes(x = Date, y = HFR, color = Method, linetype = Method)) + 
    geom_line() + 
    xlab("") + ylab("") +
    labs(color = "Source", linetype = "Source") + theme_bw() +
    ggtitle(State, subtitle=paste0("Mean delays of ", lags[[1]]," (NCHS) and ", lags[[2]], " (JHU)"))
  plot(p)
  plotlist <- append(plotlist, list(p))

}
```


```{r, fig.width=7, fig.height=8}
StatePlot <- (plotlist[[1]] + plotlist[[2]]) /
  (plotlist[[3]] + plotlist[[4]]) /
  (plotlist[[5]] +  plotlist[[6]]) +
  plot_annotation(title="State-level true & estimated HFRs",
                  theme=theme(plot.title=element_text(size=17))) +
  plot_layout(guides = "collect") &
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size=15))
StatePlot
ggsave(file.path(figure_folder, "Real", "state_level_hfrs.pdf"), 
       plot = StatePlot, device = "pdf", width = 7, height = 8) 


```


