
```{r}
data_folder <- here::here("Data", "National_Data")
code_folder <- here::here("Code", "Analysis")
figure_folder <- here::here("Figures")
source(here::here(code_folder, "helper_functions.R"))

library(patchwork)
library(ggplot2)
```

```{r}
state_data <- readRDS(here::here(data_folder, "state_dfs.RData"))
BiggestStates <- state_data[[1]]
dfList <- state_data[[2]]
oracle_lags <- state_data[[3]]

plotlist <- list()
for (i in 1:6) {
  State <- BiggestStates[i]
  dfHFR <- dfList[[i]]
  lags <- oracle_lags[[i]]
  dfHFR = dfHFR |> mutate(Method = recode_factor(Method, "Approx. GT" = "Approximate GT"))
  p <- ggplot(dfHFR, aes(x = Date, y = HFR, color = Method, linetype = Method)) + 
    geom_line() + 
    xlab("") + ylab("") +
    labs(color = "Source", linetype = "Source") + theme_bw() +
    ggtitle(State, subtitle=paste0("Mean delays of ", lags[[1]]," (NCHS) and ", lags[[2]], " (JHU)"))
  plot(p)
  plotlist <- append(plotlist, list(p))
}
```


```{r, fig.width=7, fig.height=8}
StatePlot <- (plotlist[[1]] + plotlist[[2]]) /
  (plotlist[[3]] + plotlist[[4]]) /
  (plotlist[[5]] + plotlist[[6]]) +
  plot_annotation(title="Ratio estimates and approximate ground truth",
                  theme=theme(plot.title=element_text(size=17))) +
  plot_layout(guides = "collect") &
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        legend.text = element_text(size=12),
        plot.subtitle=element_text(size=13))

StatePlot
ggsave(file.path(figure_folder, "Real", "state_level_hfrs.pdf"), 
       plot = StatePlot, device = "pdf", width = 9, height = 8.5) 
```


